### ISSUE TITLE
Let's use pkg-resource loading for this

### ISSUE THREAD

**Issue by fraudies** [databrary/pyvyu#2]
https://github.com/databrary/pyvyu/blob/73106714f0b7b53087e77207d2fe184bbf2f06a8/tests/test_pyvyu.py#L9

See: https://setuptools.readthedocs.io/en/latest/pkg_resources.html for documentation

This will be a bit more robust when loading/managing resource files.

**Comment by Xubes** [comment]
Implemented in 3d1108b179dc1c9030f47c76f4c41fb897c504f9
