### ISSUE TITLE
Why do you use parent... so far it seems to point to self always; consider removing this

### ISSUE THREAD

**Issue by fraudies** [databrary/pyvyu#3]
https://github.com/databrary/pyvyu/blob/73106714f0b7b53087e77207d2fe184bbf2f06a8/pyvyu/pyvyu.py#L119

**Comment by Xubes** [comment]
This should point to the column object that holds this cell. The Ruby API had this field, so I was keeping it for consistency. If I'm missing something please re-open this issue.
