### ISSUE TITLE
Might be useful for debugging... try to use a logger and log at debug level

### ISSUE THREAD

**Issue by fraudies** [databrary/pyvyu#4]
https://github.com/databrary/pyvyu/blob/73106714f0b7b53087e77207d2fe184bbf2f06a8/pyvyu/pyvyu.py#L42

Use the logging library  https://docs.python.org/3/library/logging.html

**Comment by Xubes** [comment]
Print statements in the main module have been replaced with log debug and warning statements. Test cases still print to stdout. Re-open if it's worth replacing those as well.
