### ISSUE TITLE
Don't see the benefit for the custom classes

### ISSUE THREAD

**Issue by fraudies** [databrary/pyvyu#8]
https://github.com/databrary/pyvyu/blob/73106714f0b7b53087e77207d2fe184bbf2f06a8/pyvyu/pyvyu.py#L30

I can't see the benefit of the custom classes Spreadsheet, Cell, Column over a representation in numpy (documentation see here: https://docs.scipy.org/doc/numpy/reference/); you can also define arrays with mixed type columns.

If you would like to have more support/functionality around views, pivot, etc. use pandas dataframes (https://pandas.pydata.org/pandas-docs/version/0.21/generated/pandas.DataFrame.html).

Rational: Both packages are widely used within the data science community and I encourage you to use these to represent the data.  This will make it much easier to inter operate with other packages and you don't have to write methods that convert the current format into one of them (either numpy arrays or pandas dataframes).

**Comment by Xubes** [comment]
Discussed with team. Provide users with pandas tables but keep classes for parity with Ruby API.

I may be stuck thinking in terms of the existing Ruby API, but having these classes allow easier manipulation of the Datavyu spreadsheet. Data processing for analyses would be done using numpy/pandas.
